CREATE TABLE faculties (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,                           
    abbreviation VARCHAR2(10) NOT NULL,                    
    students_count NUMBER DEFAULT 0 NOT NULL,              
    groups_count NUMBER DEFAULT 0 NOT NULL,                
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP         
);

CREATE TABLE groups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,                            
    faculty_id NUMBER NOT NULL,                            
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        
    students_count NUMBER DEFAULT 0 NOT NULL,              
    CONSTRAINT fk_faculty FOREIGN KEY (faculty_id) REFERENCES faculties(id) ON DELETE CASCADE
);

CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          
    first_name VARCHAR(50) NOT NULL, 
    last_name VARCHAR(50) NOT NULL,  
    group_id INT NOT NULL,           
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
);