CREATE TABLE faculties (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(200) NOT NULL,                           
    abbreviation VARCHAR2(20) NOT NULL,                    
    specialties_count NUMBER DEFAULT 0 NOT NULL,           
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP         
);

CREATE TABLE specialties (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(200) NOT NULL,                           
    abbreviation VARCHAR2(20) NOT NULL,                    
    faculty_id NUMBER NOT NULL,                            
    groups_count NUMBER DEFAULT 0 NOT NULL,                
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        
    CONSTRAINT fk_specialty_faculty FOREIGN KEY (faculty_id) REFERENCES faculties(id) ON DELETE CASCADE
);

CREATE TABLE groups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(50) NOT NULL,                            
    specialty_id NUMBER NOT NULL,                           
    students_count NUMBER DEFAULT 0 NOT NULL,              
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,         
    CONSTRAINT fk_group_specialty FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    first_name VARCHAR2(50) NOT NULL,                      
    last_name VARCHAR2(50) NOT NULL,                       
    group_id NUMBER NOT NULL,                              
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,         
    CONSTRAINT fk_student_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
);

DROP TABLE FACULTIES CASCADE CONSTRAINTS;
DROP TABLE SPECIALTIES CASCADE CONSTRAINTS;
DROP TABLE GROUPS CASCADE CONSTRAINTS;
DROP TABLE STUDENTS CASCADE CONSTRAINTS;



CREATE TABLE faculties_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(10),
    faculty_id NUMBER,
    old_name VARCHAR2(200),
    new_name VARCHAR2(200),
    old_abbreviation VARCHAR2(20),
    new_abbreviation VARCHAR2(20),
    old_specialties_count NUMBER,
    new_specialties_count NUMBER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE specialties_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(10),
    specialty_id NUMBER,
    old_name VARCHAR2(200),
    new_name VARCHAR2(200),
    old_abbreviation VARCHAR2(20),
    new_abbreviation VARCHAR2(20),
    old_faculty_id NUMBER,
    new_faculty_id NUMBER,
    old_groups_count NUMBER,
    new_groups_count NUMBER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE groups_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(10),
    group_id NUMBER,
    old_name VARCHAR2(50),
    new_name VARCHAR2(50),
    old_specialty_id NUMBER,
    new_specialty_id NUMBER,
    old_students_count NUMBER,
    new_students_count NUMBER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE students_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(10),
    student_id NUMBER,       
    old_first_name VARCHAR2(50),
    new_first_name VARCHAR2(50),
    old_last_name VARCHAR2(50), 
    new_last_name VARCHAR2(50), 
    old_group_id NUMBER,     
    new_group_id NUMBER,     
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

DROP TABLE faculties_log CASCADE CONSTRAINTS;
DROP TABLE specialties_log CASCADE CONSTRAINTS;
DROP TABLE groups_log CASCADE CONSTRAINTS;
DROP TABLE students_log CASCADE CONSTRAINTS;


CREATE TABLE triggers_state (
    trigger_name VARCHAR2(255) PRIMARY KEY,
    is_enabled NUMBER(1) DEFAULT 1
);

DROP TABLE triggers_state CASCADE CONSTRAINTS;


CREATE TABLE last_report_time (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE last_report_time CASCADE CONSTRAINTS;
