CREATE TABLE faculties (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(200) NOT NULL,                           
    abbreviation VARCHAR2(20) NOT NULL,                    
    specialties_count NUMBER DEFAULT 0 NOT NULL,           
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP         
);

CREATE TABLE specialties (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(200) NOT NULL,                           
    abbreviation VARCHAR2(20) NOT NULL,                    
    faculty_id NUMBER NOT NULL,                            
    groups_count NUMBER DEFAULT 0 NOT NULL,                
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        
    CONSTRAINT fk_specialty_faculty FOREIGN KEY (faculty_id) REFERENCES faculties(id) ON DELETE CASCADE
);

CREATE TABLE groups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR2(50) NOT NULL,                            
    specialty_id NUMBER NOT NULL,                           
    students_count NUMBER DEFAULT 0 NOT NULL,              
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,         
    CONSTRAINT fk_group_specialty FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE CASCADE
);

CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    first_name VARCHAR2(50) NOT NULL,                      
    last_name VARCHAR2(50) NOT NULL,                       
    group_id NUMBER NOT NULL,                              
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,         
    CONSTRAINT fk_student_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
);

DROP TABLE FACULTIES CASCADE CONSTRAINTS;
DROP TABLE SPECIALTIES CASCADE CONSTRAINTS;
DROP TABLE GROUPS CASCADE CONSTRAINTS;
DROP TABLE STUDENTS CASCADE CONSTRAINTS;


